/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package touchPadOptions;

import javax.swing.JOptionPane;

/**
 *
 * @author georkirm
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setTitle("Touchpad options");
        okB.setEnabled(false);
        okAndQuitB.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceBg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        welcomeT = new javax.swing.JLabel();
        choiceB3 = new javax.swing.JRadioButton();
        okB = new javax.swing.JButton();
        choiceB2 = new javax.swing.JRadioButton();
        choiceB1 = new javax.swing.JRadioButton();
        Quit = new javax.swing.JButton();
        okAndQuitB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MoreB = new javax.swing.JMenu();
        helpB = new javax.swing.JMenuItem();
        aboutB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeT.setText("Choose one of the following options:");

        choiceBg.add(choiceB3);
        choiceB3.setText("Touch pad on but desable tapping/scrolling");
        choiceB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceB3ActionPerformed(evt);
            }
        });

        okB.setText("OK");
        okB.setMaximumSize(new java.awt.Dimension(72, 30));
        okB.setMinimumSize(new java.awt.Dimension(72, 30));
        okB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBActionPerformed(evt);
            }
        });

        choiceBg.add(choiceB2);
        choiceB2.setText("Touch pad on");
        choiceB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceB2ActionPerformed(evt);
            }
        });

        choiceBg.add(choiceB1);
        choiceB1.setText("Touch pad off");
        choiceB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceB1ActionPerformed(evt);
            }
        });
        choiceB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                choiceB1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                choiceB1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                choiceB1KeyReleased(evt);
            }
        });

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        okAndQuitB.setText("Ok and quit");
        okAndQuitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAndQuitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choiceB3)
                    .addComponent(choiceB2)
                    .addComponent(choiceB1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(okB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okAndQuitB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcomeT)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcomeT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceB3)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quit)
                    .addComponent(okAndQuitB))
                .addContainerGap())
        );

        MoreB.setText("More");

        helpB.setText("Help");
        helpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBActionPerformed(evt);
            }
        });
        MoreB.add(helpB);

        aboutB.setText("About");
        aboutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBActionPerformed(evt);
            }
        });
        MoreB.add(aboutB);

        jMenuBar1.add(MoreB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    private void okBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBActionPerformed
        terminalSender temp = new terminalSender();
        if(choiceB1.isSelected()){
            temp.sendCommand(1);
        }else if(choiceB2.isSelected()){
            temp.sendCommand(0);
        }else if(choiceB3.isSelected()){
            temp.sendCommand(2);
        }else{
            temp.sendCommand(3);
        }
    }//GEN-LAST:event_okBActionPerformed

    private void choiceB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceB1ActionPerformed
        okB.setEnabled(true);
        okAndQuitB.setEnabled(true);
    }//GEN-LAST:event_choiceB1ActionPerformed

    private void choiceB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceB2ActionPerformed
        okB.setEnabled(true);
        okAndQuitB.setEnabled(true);
    }//GEN-LAST:event_choiceB2ActionPerformed

    private void choiceB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceB3ActionPerformed
        okB.setEnabled(true);
        okAndQuitB.setEnabled(true);
    }//GEN-LAST:event_choiceB3ActionPerformed

    private void helpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBActionPerformed
        JOptionPane.showMessageDialog(null, ""
                + "Choose one of the following options\n"
                + "to open or close the touchpad.\n"
                + "\t1st option turns it off\n"
                + "\t2nd option turns it on\n"
                + "\t3nd option turns it on but disables\n"
                + "\tthe scrolling and tapping"
                , "Touchpad Options", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_helpBActionPerformed

    private void aboutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBActionPerformed
        JOptionPane.showMessageDialog(null, ""
                + "Just a small java program for\n"
                + "linux laptops touchpad.\n"
                + "v1.2"
                , "Touchpad Options", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_aboutBActionPerformed

    private void okAndQuitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAndQuitBActionPerformed
        okBActionPerformed(evt);
        dispose();
    }//GEN-LAST:event_okAndQuitBActionPerformed

    private void choiceB1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_choiceB1KeyTyped

    }//GEN-LAST:event_choiceB1KeyTyped

    private void choiceB1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_choiceB1KeyReleased

    }//GEN-LAST:event_choiceB1KeyReleased

    private void choiceB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_choiceB1KeyPressed
        if(evt.isShiftDown()){
            choiceB1.doClick();
        }
    }//GEN-LAST:event_choiceB1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MoreB;
    private javax.swing.JButton Quit;
    private javax.swing.JMenuItem aboutB;
    private javax.swing.JRadioButton choiceB1;
    private javax.swing.JRadioButton choiceB2;
    private javax.swing.JRadioButton choiceB3;
    private javax.swing.ButtonGroup choiceBg;
    private javax.swing.JMenuItem helpB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okAndQuitB;
    private javax.swing.JButton okB;
    private javax.swing.JLabel welcomeT;
    // End of variables declaration//GEN-END:variables
}
